---
title: "Antes del tutorial"
output:
  html_document:
    toc: false
---

Para participar en este taller podés instalar (o tal vez actualizar) R (>4.0) y Rstudio (revisa las instrucción más abajo) o usar una instancia de R en RStudio Cloud.

## Usando RStudio Cloud

Si querés usar RStudio Cloud necesitarás una cuenta gratuita. Ingresá a [rstudio.cloud/](https://rstudio.cloud/) y seguí las instrucciones para registrarte. Tené en cuenta que la cuenta gratuita tiene un límite de uso de 25 horas por mes, te recomendamos no usar todas las horas antes del taller.

Durante el taller compartiremos un link a un proyecto de RStudio listo para usar. No es necesario que hagas nada más. 

## Instalando R y RStudio

Para instalar R y RStudio sigue las instrucciones en [estos videos](https://www.youtube.com/playlist?list=PLRPB0ZzEYegOZivdelOuEn-R-XUN-DOjd) de [Danielle Navarro](https://djnavarro.net/).

Durante el taller compartiremos un link para descargar un proyecto de RStudio zipeado (es importante que puedas descomprimirlo en tu computadora) con todos los materiales necesarios para participar.
